all:
  children:
    apps:
      hosts:
        prod-apps-01:
          ansible_user: fedora
          ansible_host: prod-apps-01.home.hovirix.dev
    data:
      hosts:
        prod-data-01:
          ansible_user: fedora
          ansible_host: prod-data-01.home.hovirix.dev

    edge:
      hosts:
        prod-edge-01:
          ansible_user: fedora
          ansible_host: prod-edge-01.home.hovirix.dev

    idp:
      hosts:
        prod-idp-01:
          ansible_user: fedora
          ansible_host: prod-idp-01.home.hovirix.dev
