- name: Create Podman secrets
  containers.podman.podman_secret:
    state: present
    force: true
    name: "{{ item.name }}"
    data: "{{ item.value }}"
  loop: "{{ podman_secrets_items }}"
  loop_control:
    label: "{{ item.name }}"
