---
workloads_root: "{{ playbook_dir }}/../../../workloads"
secrets_root: "{{ playbook_dir }}/../../../secrets/workloads"

apps_secret_files:
  postgres: "{{ secrets_root }}/postgres.sops.yaml"
  valkey: "{{ secrets_root }}/valkey.sops.yaml"
  paperless: "{{ secrets_root }}/paperless.sops.yaml"
  vaultwarden: "{{ secrets_root }}/vaultwarden.sops.yaml"

apps_podman_secrets:
  - name: postgres_immich_username
    value: "{{ sops_postgres.postgres.immich.username }}"
  - name: postgres_immich_password
    value: "{{ sops_postgres.postgres.immich.password }}"
  - name: valkey_username
    value: "{{ sops_valkey.valkey.username }}"
  - name: valkey_password
    value: "{{ sops_valkey.valkey.password }}"

  - name: postgres_paperless_username
    value: "{{ sops_postgres.postgres.paperless.username }}"
  - name: postgres_paperless_password
    value: "{{ sops_postgres.postgres.paperless.password }}"
  - name: paperless_secret_key
    value: "{{ sops_paperless.paperless.secret_key }}"
  - name: paperless_socialaccount_providers
    value: "{{ sops_paperless.paperless.socialaccount_providers }}"

  - name: postgres_vaultwarden_username
    value: "{{ sops_postgres.postgres.vaultwarden.username }}"
  - name: postgres_vaultwarden_password
    value: "{{ sops_postgres.postgres.vaultwarden.password }}"
  - name: vaultwarden_installation_id
    value: "{{ sops_vaultwarden.vaultwarden.installation.id }}"
  - name: vaultwarden_installation_key
    value: "{{ sops_vaultwarden.vaultwarden.installation.key }}"
    
apps_quadlet_dir: /etc/containers/systemd

apps_quadlet:
  - name: immich
    src: "{{ workloads_root }}/apps/immich"
  - name: paperless
    src: "{{ workloads_root }}/apps/paperless"
  - name: vaultwarden
    src: "{{ workloads_root }}/apps/vaultwarden"
