repos:
  - repo: local
    hooks:
      - id: nix-fmt
        name: nix fmt
        entry: nix fmt
        language: system
        pass_filenames: false
        always_run: true
      - id: trivy-secret
        name: trivy secret scan
        entry: trivy --config security/trivy.yaml fs --scanners secret .
        language: system
        pass_filenames: false
        always_run: true
