version: "3"

silent: true

includes:
  check:
    taskfile: operations/taskfiles/check.yml

  infra:
    taskfile: operations/taskfiles/infra.yml

  pve:
    taskfile: operations/taskfiles/pve.yml

  swarm:
    taskfile: operations/taskfiles/swarm.yml

  platform:
    taskfile: operations/taskfiles/platform.yml

tasks:
  check:
    desc: Run all local validation
    cmds:
      - task: check:lint
      - task: check:security

  deploy:
    desc: Deploy/update all platform workloads
    cmds:
      - task: platform:deploy

  bootstrap:
    desc: Converge the complete homelab from infrastructure to platform
    cmds:
      - task: infra:apply
      - task: pve:apply
      - task: swarm:init
      - task: platform:deploy
