version: "3"

silent: true

includes:
  lint:
    flatten: true
    taskfile: operations/taskfiles/lint.yml

  configure:
    taskfile: operations/taskfiles/configure.yml

  security:
    taskfile: operations/taskfiles/security.yml

  provision:
    taskfile: operations/taskfiles/provision.yml

  swarm:
    taskfile: operations/taskfiles/swarm.yml

tasks:
  security:
    desc: Run all local security checks
    cmds:
      - task: security:check
