[global]
excludes = ["secrets/**"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["**/*.nix"]

[formatter.prettier]
command = "prettier"
includes = ["**/*.{css,graphql,html,js,json,json5,jsonc,jsx,less,md,mdx,scss,ts,tsx,vue}"]

[formatter.ruff]
command = "ruff"
options = ["format"]
includes = ["**/*.py"]

[formatter.shfmt]
command = "shfmt"
includes = ["operations/scripts/*.sh"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["**/*.toml"]

[formatter.yamlfmt]
command = "yamlfmt"
options = ["-formatter", "type=basic", "-formatter", "retain_line_breaks_single=true"]
includes = ["**/*.{bu,yaml,yml}"]

[formatter.opentofu]
command = "tofu"
options = ["fmt"]
includes = ["**/*.tf", "**/*.tfvars"]
