---
services_root: "{{ playbook_dir }}/../../../services"
secrets_root: "{{ playbook_dir }}/../../../security/secrets/services"

data_secret_files:
  postgres: "{{ secrets_root }}/postgres.sops.yaml"
  valkey: "{{ secrets_root }}/valkey.sops.yaml"

data_podman_secrets:
  - name: postgres_admin_password
    value: "{{ sops_postgres.postgres.admin_password }}"
  - name: postgres_authentik_username
    value: "{{ sops_postgres.postgres.authentik.username }}"
  - name: postgres_authentik_password
    value: "{{ sops_postgres.postgres.authentik.password }}"
  - name: postgres_grafana_username
    value: "{{ sops_postgres.postgres.grafana.username }}"
  - name: postgres_grafana_password
    value: "{{ sops_postgres.postgres.grafana.password }}"
  - name: postgres_immich_username
    value: "{{ sops_postgres.postgres.immich.username }}"
  - name: postgres_immich_password
    value: "{{ sops_postgres.postgres.immich.password }}"
  - name: postgres_paperless_username
    value: "{{ sops_postgres.postgres.paperless.username }}"
  - name: postgres_paperless_password
    value: "{{ sops_postgres.postgres.paperless.password }}"
  - name: postgres_vaultwarden_username
    value: "{{ sops_postgres.postgres.vaultwarden.username }}"
  - name: postgres_vaultwarden_password
    value: "{{ sops_postgres.postgres.vaultwarden.password }}"
  - name: valkey_username
    value: "{{ sops_valkey.valkey.username }}"
  - name: valkey_password
    value: "{{ sops_valkey.valkey.password }}"

data_quadlet_dir: /etc/containers/systemd

data_quadlet:
  - name: postgres
    src: "{{ services_root }}/postgres"
  - name: valkey
    src: "{{ services_root }}/valkey"

data_srv_layout:
  - name: postgres
