persistence:
  enabled: false

grafana.ini:
  auth.anonymous:
    enabled: false
  server:
    domain: grafana.home.hovirix.dev
    root_url: https://grafana.home.hovirix.dev/
  users:
    allow_sign_up: false

datasources:
  datasources.yaml:
    apiVersion: 1
    prune: true
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false

      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
        editable: false

sidecar:
  dashboards:
    enabled: true
    searchNamespace:
      - ALL
    label: grafana_dashboard
    labelValue: "1"
