all:
  children:
    apps:
      hosts:
        prod-apps-01:
          ansible_user: fedora
          ansible_host: 10.20.0.50
    data:
      hosts:
        prod-data-01:
          ansible_user: fedora
          ansible_host: 10.20.0.20

    edge:
      hosts:
        prod-edge-01:
          ansible_user: fedora
          ansible_host: 10.20.0.10

    idp:
      hosts:
        prod-idp-01:
          ansible_user: fedora
          ansible_host: 10.20.0.15
