all:
  vars:
    ansible_user: fedora
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    apps:
      hosts:
        prod-apps-01:
          ansible_host: 10.20.0.50
    data:
      hosts:
        prod-data-01:
          ansible_host: 10.20.0.20
