#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 <<SQL
CREATE ROLE authentik LOGIN PASSWORD '${POSTGRES_AUTHENTIK_PASSWORD}';
CREATE DATABASE authentik OWNER authentik;
REVOKE ALL ON DATABASE authentik FROM PUBLIC;

CREATE ROLE immich LOGIN PASSWORD '${POSTGRES_IMMICH_PASSWORD}';
CREATE DATABASE immich OWNER immich;
REVOKE ALL ON DATABASE immich FROM PUBLIC;
\c immich
CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS earthdistance;

CREATE ROLE paperless LOGIN PASSWORD '${POSTGRES_PAPERLESS_PASSWORD}';
CREATE DATABASE paperless OWNER paperless;
REVOKE ALL ON DATABASE paperless FROM PUBLIC;

CREATE ROLE grafana LOGIN PASSWORD '${POSTGRES_GRAFANA_PASSWORD}';
CREATE DATABASE grafana OWNER grafana;
REVOKE ALL ON DATABASE grafana FROM PUBLIC;

CREATE ROLE vaultwarden LOGIN PASSWORD '${POSTGRES_VAULTWARDEN_PASSWORD}';
CREATE DATABASE vaultwarden OWNER vaultwarden;
REVOKE ALL ON DATABASE vaultwarden FROM PUBLIC;
SQL
