apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:ppqcqDSyqSd0mluyT+UbGKxB2ce9UarLpbhcBiv1kQ70,iv:rZtqryVAp1aFLyhM48GtaXKFgAlE8TsBmV9XYnctnOM=,tag:VgWadji9O6bFXy+fkI1gug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Sk96WmxYeFFFd1VQRklQ
        bXJDbVpHdXR5YllscTIvM0c0WEVnbjV4ekFzCmN4bk9qWW55TmhqVXI0aVJsazFw
        U3BxeWpQWGdLamJ3NFJwWnJjMTdzdW8KLS0tIE5QbFNZdEgxVGpaOUNrTnlVNENX
        SUtBUGJKZkxRMVA3TnV1Nys4QS9jV0kK0CIQHF7U1dmh9Gdy/uVAzJNaoxUiNfch
        6GNBLatc017C33WqeaisXlYBJ5sRpLRjgrdvx2NjyR3jtZxD/6EbHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1997u9c7xd73r2dmkrs5tu2jjwfh8xxn4uc333rdlgafhpegg596sl75qyk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T11:16:15Z"
  mac: ENC[AES256_GCM,data:VLlgcvga536/KcHfXXpSNMYFNRx0WTHJU5AOGbc0ZhChoFwpyF3Q87LhoEs64YnlfkoFB/T2n/mw7I7iTSbTjVVOkRZYB6uuMUoDqqoAA5lUxH1Hgmxgq4nsx32VPRHqiTqyz90MFgY2qFHTYAZ9Sr1aGFr8tmNOWgw4vH7KuZ0=,iv:3OWgie+csENtax45kriHPOWYLE5svxyO0mGuLXHjs3A=,tag:lJm5aUUsCulllFtRl3dDMw==,type:str]
  pgp:
    - created_at: "2026-07-10T11:16:15Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DKaLs6sJalgMSAQdALyzoliltocro7mveJa2jcHynaR1dTy6nLxS90S6j92ww
        Y9AtYUiP7EMHRhwGM9+9kbnWpY8/6HwN9KtFYYCsP168Sk/dykU4dQBin/TenhDP
        0lwBweQHpuULf/VUURf9I5KNatFshltaKL5Y5/R1+FkcNkM5oHalUo/oG3pyNgpM
        e8924GIVxSPzS2qNCLan8y+WFgnPF1xsZckTKlZUlMpZjwvnBtQW5+vOaWPZXQ==
        =ypjV
        -----END PGP MESSAGE-----
      fp: 82F33E760DDCEB7BB83E2EC3AAC0F2E854677A6F
  version: 3.13.1
