[[language]]
name = "ini"
file-types = ["ini", "containers", "volume", "network", "env.tftpl"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml", "bu"]

[[language]]
name = "hcl"
file-types = ["hcl", "tf", "tftpl"]
