apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:8VDKzbO4RUADPhbEGQiIZDehVM2xuyKbLDFbWRdH/bez,iv:V9hrX3fX6kNHfS/9B9H/3sftrPxhkjfZx4vGWehPOxM=,tag:/mEOvDp9xmzXMyg07+Xq/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN2oxSnV3YnlTL2h6ZWV4
        dklrUDlaTGRkV2dVNUQ2MUFtZm9DcWJGSXpFClRRdUh6U2JORGoyRlRaSjgzWVA1
        VEdPbVNmZ2tjSWREQkc2Zy9UMHBhQTAKLS0tIEJXcGRURkpYOTRjTmNwMVNnMWE5
        cWlmWU9aS0t4WTlZcUw5L053Y0FzRHcKWNtvj8qC0RYERt35+vdT07i7LLs62AJP
        d25V3XRpWB6ZTGuARpsecCb4dVc4LzQvWEY3lxiKLTJXMxmk+/juJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13h4qjyp2axfvzmjzengglzv2h40z3gz88aygdu02y025yg2phqkqjtfp28
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T14:32:43Z"
  mac: ENC[AES256_GCM,data:9kYu6LqjzwldvMs00PEUylpO0zR2Hb8Cam4vhT88ZsetCFw1I5XQeV+wB/OI4Los4qzY/mGW2OYc/9jUWGCWl6SW3kIWM3uWfcduftnQjWGYBW2Z9JHNYQOlHDp8F8lDMsUWJDuxIN1i6S3/BxcnsLnb3hpX5KKSihKcYISYnms=,iv:NISax3XRGZn6MhJNtRkdn/txf8xCIdGa9dpbeNYaDCY=,tag:d9v6Iye/HD64xsQqgRtFQw==,type:str]
  pgp:
    - created_at: "2026-07-12T14:25:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DKaLs6sJalgMSAQdAt45Ap8Qz3WqUUYa6ZbEuRidDrBjvQQ3nB8LjBaT1pCEw
        azGt9gk0wDGaXUhIHuLcINzUSiP9dy7wtBw0Mh9kEXKptqHHO9OKByqBdugd7101
        0l4BzdB7sxBX6Xtk0d2P5c/uEGGdbtdKr290hf6ExbJhXck8lud77FRmKDAdewps
        QTdN64OcI2ha5SjGdlyaW/tzM1JAxQs9S6JwrluJk7pEkgi7o//6Vq84XZI7PEXB
        =dyIz
        -----END PGP MESSAGE-----
      fp: 82F33E760DDCEB7BB83E2EC3AAC0F2E854677A6F
  version: 3.13.1
