pve:
  system:
    enabled: true
    domain: home.hovirix.dev
    timezone: Etc/UTC

  repositories:
    enabled: true

  updates:
    enabled: true
    upgrade: true
    reboot: true

  ssh:
    enabled: true
    permit_root_login: prohibit-password
    root_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPTAawDXqCZS9g+Q+2/L8chJ5gD97WLaKKi6DG4nccuA openpgp:0x3602CA24

  wake_on_lan:
    enabled: true

  networking:
    enabled: true
    management:
      vlan: 20
      gateway: 10.20.0.1
    allowed_vlans:
      - id: 20
        name: management
      - id: 40
        name: kubernetes
      - id: 60
        name: air-gapped-vms

  storage:
    enabled: true
    zpool: rpool
    dataset: rpool/data
    min_pool_size_gib: 1500
    autotrim: true
    dataset_properties:
      compression: lz4
      atime: "off"

  kernel:
    enabled: true
    manage_cmdline: true
    iommu:
      enabled: true
    vfio:
      enabled: true

  firewall:
    enabled: false

  certificates:
    enabled: true

  monitoring:
    enabled: false

  notifications:
    enabled: true
    target_name: hxlab-smtp
    matcher_name: hxlab-alerts
    mailto: homelab@hovirix.dev
    from_address: proxmox@hovirix.dev
    smtp_mode: starttls
    match_severity:
      - warning
      - error

  backup:
    enabled: false
    target_type: nfs
    retention:
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 12

  cluster:
    enabled: false
    planned_nodes:
      - pve1
      - pve2
      - pve3

  api:
    enabled: true
    roles:
      - name: OpenTofuProv
        privileges:
          - Datastore.AllocateSpace
          - Datastore.AllocateTemplate
          - Datastore.Audit
          - Sys.Audit
          - VM.Allocate
          - VM.Audit
          - VM.Config.CDROM
          - VM.Config.CPU
          - VM.Config.Disk
          - VM.Config.HWType
          - VM.Config.Memory
          - VM.Config.Network
          - VM.Config.Options
          - VM.PowerMgmt

    users:
      - userid: opentofu@pve
        comment: OpenTofu lifecycle user
        token:
          id: opentofu
          comment: OpenTofu lifecycle token
          privsep: false
          regenerate: false
        acl:
          path: /
          role: OpenTofuProv
