apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-gateway-api
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/gateway-api
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cilium
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/cilium
  prune: true
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/cert-manager
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: networking-cilium
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-certificates
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/certificates
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: networking-cert-manager
    - name: networking-gateway-api
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-traefik
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/traefik
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: networking-certificates
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: traefik
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
