apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tls-install
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/tls/install
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: connectivity
  sourceRef:
    kind: GitRepository
    name: homelab

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tls-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/tls/config
  prune: true
  dependsOn:
    - name: tls-install
  sourceRef:
    kind: GitRepository
    name: homelab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
