all:
  children:
    hosts:
      hosts:
        pve1:
          ansible_host: pve1.home.hovirix.dev
          ansible_user: root

    proxmox:
      hosts:
        pve1:
          ansible_host: pve1.home.hovirix.dev
          ansible_user: root
        # pve2:
        # ansible_host: pve2.home.hovirix.dev
        # ansible_user: root
        # pve3:
        # ansible_host: pve3.home.hovirix.dev
        # ansible_user: root
