api_token: ENC[AES256_GCM,data:TNhFn3A5PM1QqFVWJDUshl5T5ynJQhejmYE1CXIiD/pYq55a7Y0LsC4EifAovVFgvAGDBzE=,iv:uiqViBiequqt6n0GRkgcRrthAc/cQye2rZu60LQOlRQ=,tag:DkCygTMxoAey88pskGvDgA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyBGUVQy
            MVpDRC8vTVNMTmNqOS9LWlRNQTBsUmM2ZWFGSXpKUmM1VGlQMkc0CkVNZmFTWmlt
            cys3UzBIbi80aHIxUk5aMGZTa3Y1dUJUNzZBbnhsZ21STUkKLS0tIFhOSkxnK1px
            QXZzWmZva2xrUnFKYmMyZTZNZVNFUkozeVRNUUZFc1R0cVkKdVCwyToZWfVKR2Pw
            eqibs+SYf/9NU1qBlVsDzkASz4M93RlNkPtY5QK5RmZYDhEavICyahvMFaeUEf+Z
            5TgJhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T01:57:31Z"
    mac: ENC[AES256_GCM,data:viGtfKQ7RMaStpxL5w+TcMSbEll759oS/c1HzPMIQXIoLVNWYcbogOUuGcuXf3IwBHdFYo1iGaYudLDt7M+nCWhzgIQi3gaH2EIe/fkdBANzTwMK8vImpaRqHJVsJ0Ro6W9rrY5Uuve1Tq46NBB1T8M8i/VpATUaPu6Dyf1r7Vk=,iv:PU4vpfx7OtK77RoF9bjd/kbAwo5d75KuG7nJKhH/daA=,tag:yRVs4ftrEK7oQpSClTqxtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
