auth_enabled: false

common:
  path_prefix: /loki
  replication_factor: 1

  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

  ring:
    kvstore:
      store: inmemory

compactor:
  retention_enabled: true
  delete_request_store: filesystem

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

pattern_ingester:
  enabled: true

limits_config:
  retention_period: 720h # 30 days
