- name: Create OpenTofu API user
  ansible.builtin.command:
    argv:
      - pveum
      - user
      - add
      - opentofu@pve
      - --comment
      - OpenTofu VM lifecycle
  register: datacenter_api_user
  failed_when:
    - datacenter_api_user.rc != 0
    - "'already exists' not in datacenter_api_user.stderr"
  changed_when: datacenter_api_user.rc == 0
  run_once: true

- name: Assign VM administration permissions
  ansible.builtin.command:
    argv:
      - pveum
      - acl
      - modify
      - /
      - --users
      - opentofu@pve
      - --roles
      - PVEVMAdmin
  changed_when: false
  run_once: true

- name: Assign ISO datastore administration permissions
  ansible.builtin.command:
    argv:
      - pveum
      - acl
      - modify
      - /storage/local
      - --users
      - opentofu@pve
      - --roles
      - PVEDatastoreAdmin
  changed_when: false
  run_once: true

- name: Assign VM disk datastore administration permissions
  ansible.builtin.command:
    argv:
      - pveum
      - acl
      - modify
      - /storage/local-zfs
      - --users
      - opentofu@pve
      - --roles
      - PVEDatastoreAdmin
  changed_when: false
  run_once: true

- name: Create OpenTofu API token
  ansible.builtin.command:
    argv:
      - pveum
      - user
      - token
      - add
      - opentofu@pve
      - opentofu
      - --privsep
      - "0"
      - --comment
      - OpenTofu VM lifecycle
      - --output-format
      - json
  register: datacenter_api_token
  failed_when:
    - datacenter_api_token.rc != 0
    - "'already exists' not in datacenter_api_token.stderr"
  changed_when: datacenter_api_token.rc == 0
  no_log: true
  run_once: true

- name: Display generated OpenTofu API token
  ansible.builtin.debug:
    msg:
      token_id: opentofu@pve!opentofu
      token_secret: "{{ (datacenter_api_token.stdout | from_json).value }}"
  when: datacenter_api_token.rc == 0
  run_once: true
