- name: Order ACME certificates
  ansible.builtin.command:
    argv:
      - pvenode
      - acme
      - cert
      - order
      - --force
      - "1"
  changed_when: true
  delegate_to: "{{ item }}"
  loop: "{{ ansible_play_hosts_all }}"
  run_once: true
