- name: Configure Proxmox hosts
  hosts: hosts

  roles:
    - role: common
      when: host.system.enabled | bool
      tags: [common]

    - role: repositories
      when: host.repositories.enabled | bool
      tags: [repositories]

    - role: ssh
      when: host.ssh.enabled | bool
      tags: [ssh]

    - role: wake_on_lan
      when: host.wake_on_lan.enabled | bool
      tags: [wake-on-lan]

    - role: storage
      when: host.storage.enabled | bool
      tags: [storage]

    - role: kernel
      when: host.kernel.enabled | bool
      tags: [kernel]
