- name: Configure Proxmox VE datacenter
  hosts: nodes
  run_once: true

  tasks:
    - name: Configure Proxmox VE storage
      ansible.builtin.import_role:
        name: datacenter
        tasks_from: storage
      tags: [storage]

    - name: Configure Proxmox VE backup jobs
      ansible.builtin.import_role:
        name: datacenter
        tasks_from: backup
      tags: [backup]

    - name: Configure Proxmox VE API resources
      ansible.builtin.import_role:
        name: datacenter
        tasks_from: api
      tags: [api]

    - name: Configure Proxmox VE datacenter certificates
      ansible.builtin.import_role:
        name: datacenter
        tasks_from: certificates
      tags: [certificates]

    - name: Configure Proxmox VE notifications
      ansible.builtin.import_role:
        name: datacenter
        tasks_from: notifications
      tags: [notifications]
