- name: Configure hosts
  hosts: nodes

  tasks:
    - name: Configure host system
      ansible.builtin.import_role:
        name: host
        tasks_from: system
      tags: [system]

    - name: Configure host repositories
      ansible.builtin.import_role:
        name: host
        tasks_from: repositories
      tags: [repositories]

    - name: Configure host SSH
      ansible.builtin.import_role:
        name: host
        tasks_from: ssh
      tags: [ssh]

    - name: Configure host Wake-on-LAN
      ansible.builtin.import_role:
        name: host
        tasks_from: wake_on_lan
      tags: [wake-on-lan]

    - name: Configure host ZFS
      ansible.builtin.import_role:
        name: host
        tasks_from: zfs
      tags: [zfs]

    - name: Configure host kernel
      ansible.builtin.import_role:
        name: host
        tasks_from: kernel
      tags: [kernel]

    - name: Configure host sysctl
      ansible.builtin.import_role:
        name: host
        tasks_from: sysctl
      tags: [sysctl]

- name: Configure host networking
  hosts: nodes
  serial: 1

  tasks:
    - name: Configure host networking
      ansible.builtin.import_role:
        name: host
        tasks_from: networking
      tags: [networking]

- name: Maintain hosts
  hosts: nodes
  serial: 1

  tasks:
    - name: Configure host updates
      ansible.builtin.import_role:
        name: host
        tasks_from: updates
      tags: [updates]
