- name: Maintain Proxmox nodes
  hosts: nodes
  serial: 1

  tasks:
    - name: Configure node updates
      ansible.builtin.import_role:
        name: node
        tasks_from: updates
      when: host.updates.enabled | bool
      tags: [updates]
