- name: Migrate Proxmox nodes to VLAN networking
  hosts: nodes
  serial: 1

  tasks:
    - name: Configure node networking
      ansible.builtin.import_role:
        name: node
        tasks_from: networking
      when: node.networking.enabled | bool
      tags: [networking]
