- name: Configure Proxmox nodes
  hosts: nodes

  tasks:
    - name: Configure node system
      ansible.builtin.import_role:
        name: node
        tasks_from: common
      tags: [common]

    - name: Configure node repositories
      ansible.builtin.import_role:
        name: node
        tasks_from: repositories
      tags: [repositories]

    - name: Configure node SSH
      ansible.builtin.import_role:
        name: node
        tasks_from: ssh
      tags: [ssh]

    - name: Configure node Wake-on-LAN
      ansible.builtin.import_role:
        name: node
        tasks_from: wake_on_lan
      tags: [wake-on-lan]

    - name: Configure node storage
      ansible.builtin.import_role:
        name: node
        tasks_from: storage
      tags: [storage]

    - name: Configure node kernel
      ansible.builtin.import_role:
        name: node
        tasks_from: kernel
      tags: [kernel]

- name: Configure Proxmox node networking
  hosts: nodes
  serial: 1

  tasks:
    - name: Configure node networking
      ansible.builtin.import_role:
        name: node
        tasks_from: networking
      tags: [networking]

- name: Maintain Proxmox nodes
  hosts: nodes
  serial: 1

  tasks:
    - name: Configure node updates
      ansible.builtin.import_role:
        name: node
        tasks_from: updates
      tags: [updates]
