- name: Configure Proxmox resources
  hosts: nodes

  tasks:
    - name: Configure Proxmox repositories
      ansible.builtin.import_role:
        name: proxmox
        tasks_from: repositories
      tags: [repositories]

    - name: Configure Proxmox storage
      ansible.builtin.import_role:
        name: proxmox
        tasks_from: storage
      tags: [storage]

    - name: Configure Proxmox API resources
      ansible.builtin.import_role:
        name: proxmox
        tasks_from: api
      tags: [api]

    - name: Configure Proxmox certificates
      ansible.builtin.import_role:
        name: proxmox
        tasks_from: certificates
      tags: [certificates]

    - name: Configure Proxmox notifications
      ansible.builtin.import_role:
        name: proxmox
        tasks_from: notifications
      tags: [notifications]
