- name: Configure Proxmox VE nodes
  hosts: nodes
  serial: 1

  roles:
    - system
    - repositories
    - ssh
    - wake_on_lan
    - zfs
    - kernel
    - networking
    - automatic_updates
    - storage
    - acme
    - opentofu_access
    - notifications
    - backup
