- name: Enable IOMMU kernel parameters
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    regexp: "^(.*?)(?:\\s+amd_iommu=on)?(?:\\s+iommu=pt)?$"
    line: '\1 amd_iommu=on iommu=pt'
    backrefs: true
  notify: Refresh bootloader

- name: Configure VFIO modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/vfio.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
  notify: Update initramfs
