- name: Configure node system
  ansible.builtin.import_tasks: common.yml
  when: node.system.enabled | bool
  tags: [common]

- name: Configure node repositories
  ansible.builtin.import_tasks: repositories.yml
  when: node.repositories.enabled | bool
  tags: [repositories]

- name: Configure node SSH
  ansible.builtin.import_tasks: ssh.yml
  when: node.ssh.enabled | bool
  tags: [ssh]

- name: Configure node Wake-on-LAN
  ansible.builtin.import_tasks: wake_on_lan.yml
  when: node.wake_on_lan.enabled | bool
  tags: [wake-on-lan]

- name: Configure node storage
  ansible.builtin.import_tasks: storage.yml
  when: node.storage.enabled | bool
  tags: [storage]

- name: Configure node kernel
  ansible.builtin.import_tasks: kernel.yml
  when: node.kernel.enabled | bool
  tags: [kernel]
