- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: dist
  when: host.updates.upgrade | bool

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: node_updates_reboot_required

- name: Reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 900
  when:
    - host.updates.reboot | bool
    - node_updates_reboot_required.stat.exists
