apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: authentik
  namespace: database
spec:
  cluster:
    name: postgresql
  name: authentik
  login: true
  superuser: false
  createdb: false
  createrole: false
  replication: false
  passwordSecret:
    name: authentik-db
  databaseRoleReclaimPolicy: retain
