ingressClass:
  enabled: false

providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  listeners:
    web:
      port: 80
      protocol: HTTP
      namespacePolicy: All
    websecure:
      port: 443
      protocol: HTTPS
      namespacePolicy: All
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: home-hovirix-dev-tls
          namespace: cert-manager

ports:
  web:
    port: 80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    port: 443

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.40.0.200

api:
  dashboard: false

log:
  level: INFO
