ingressClass:
  enabled: false

providers:
  kubernetesCRD:
    enabled: false

  kubernetesIngress:
    enabled: false

  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy:
        from: All

    websecure:
      port: 8443
      protocol: HTTPS
      namespacePolicy:
        from: All
      mode: Terminate
      certificateRefs:
        - group: ""
          kind: Secret
          name: home-hovirix-dev-tls
          namespace: cert-manager

api:
  dashboard: false

accessLog:
  enabled: true
  format: json

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

service:
  annotations:
    lbipam.cilium.io/ips: 10.40.0.200
  labels:
    networking.hovirix.dev/address-pool: internal
