---
- name: Install quadlet applications
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ quadlet_dir }}"
  loop: "{{ quadlet_workloads }}"
  loop_control:
    label: "{{ item.name }}"

- name: Load quadlet applications
  ansible.builtin.systemd_service:
    daemon_reload: true
