apiVersion: 1

datasources:
  - name: metrics
    uid: metrics
    type: prometheus
    url: http://victoriametrics:8428
    isDefault: true

  - name: logs
    uid: logs
    type: loki
    url: http://loki:3100
