- name: Remove unnecessary Proxmox repository files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/pve-enterprise.list
    - /etc/apt/sources.list.d/ceph.list
    - /etc/apt/sources.list.d/pve-enterprise.sources
    - /etc/apt/sources.list.d/ceph.sources

- name: Configure Proxmox no-subscription repository
  ansible.builtin.template:
    src: proxmox.sources.j2
    dest: /etc/apt/sources.list.d/proxmox.sources
    owner: root
    group: root
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
