apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: connectivity
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/connectivity/install
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: connectivity-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./platform/networking/connectivity/config
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: connectivity
  sourceRef:
    kind: GitRepository
    name: homelab
