services:
  parent:
    image: netdata/netdata:v2.11.0

    entrypoint:
      - /etc/netdata/netdata-start.sh

    environment:
      DISABLE_TELEMETRY: "1"
      NETDATA_HEALTHCHECK_TARGET: http://localhost:19998/api/v1/info
      NETDATA_STREAM_ROLE: parent

    configs:
      - source: parent_config
        target: /etc/netdata/netdata.conf
      - source: netdata_start
        target: /etc/netdata/netdata-start.sh
        mode: 0555

    secrets:
      - netdata_streaming_api_key

    networks:
      - netdata
      - traefik-public

    ports:
      - target: 19999
        published: 19999
        protocol: tcp
        mode: ingress

    volumes:
      - type: bind
        source: /var/mnt/swarm/netdata/lib
        target: /var/lib/netdata
      - type: bind
        source: /var/mnt/swarm/netdata/cache
        target: /var/cache/netdata

    deploy:
      replicas: 1

      labels:
        - traefik.enable=true
        - traefik.http.routers.netdata.rule=Host(`netdata.hovirix.dev`)
        - traefik.http.routers.netdata.entrypoints=websecure
        - traefik.http.routers.netdata.tls=true
        - traefik.http.routers.netdata.tls.certresolver=cloudflare
        - traefik.http.services.netdata.loadbalancer.server.port=19998

      update_config:
        order: stop-first
        failure_action: rollback

      rollback_config:
        order: stop-first

      restart_policy:
        condition: on-failure

  child:
    image: netdata/netdata:v2.11.0

    hostname: "{{.Node.Hostname}}"

    entrypoint:
      - /etc/netdata/netdata-start.sh

    environment:
      DISABLE_TELEMETRY: "1"
      NETDATA_HEALTHCHECK_TARGET: cli
      NETDATA_STREAM_ROLE: child
      NETDATA_STREAM_DESTINATION: swarm-01.home.hovirix.dev:19999 swarm-02.home.hovirix.dev:19999 swarm-03.home.hovirix.dev:19999

    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE

    configs:
      - source: child_config
        target: /etc/netdata/netdata.conf
      - source: netdata_start
        target: /etc/netdata/netdata-start.sh
        mode: 0555

    secrets:
      - netdata_streaming_api_key

    networks:
      - host

    volumes:
      - type: bind
        source: /
        target: /host/root
        read_only: true
        bind:
          propagation: rslave
      - type: bind
        source: /etc/passwd
        target: /host/etc/passwd
        read_only: true
      - type: bind
        source: /etc/group
        target: /host/etc/group
        read_only: true
      - type: bind
        source: /etc/hostname
        target: /host/etc/hostname
        read_only: true
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
      - type: bind
        source: /etc/os-release
        target: /host/etc/os-release
        read_only: true
      - type: bind
        source: /var/log
        target: /host/var/log
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /run/dbus
        target: /run/dbus
        read_only: true

    deploy:
      mode: global

      update_config:
        order: stop-first
        failure_action: rollback

      rollback_config:
        order: stop-first

      restart_policy:
        condition: on-failure

networks:
  netdata:
    driver: overlay

  traefik-public:
    name: ingress_traefik-public
    external: true

  host:
    external: true
    name: host

configs:
  parent_config:
    file: ./configs/netdata-parent.conf

  child_config:
    file: ./configs/netdata-child.conf

  netdata_start:
    file: ./configs/netdata-start.sh

secrets:
  netdata_streaming_api_key:
    external: true
