- name: Configure kernel command line
  ansible.builtin.template:
    src: cmdline.j2
    dest: /etc/kernel/cmdline
    owner: root
    group: root
    mode: "0644"
  notify: Refresh bootloader
  when:
    - proxmox_kernel_manage | bool

- name: Configure VFIO modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/vfio.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
  notify: Update initramfs
  when:
    - proxmox_kernel_manage | bool
    - proxmox_enable_vfio | bool
