apiVersion: v1
kind: Secret
metadata:
  name: authentik-db
  namespace: database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:bPi1ui31Uddj,iv:LgIhNGA8I/w+nyKz8CIRU8wQFRNQkPF48I8t0ue6rqY=,tag:BygTxQ+RPZtPT6ArfCQPnA==,type:str]
  password: ENC[AES256_GCM,data:fHIgVMs4okc4mbllooPdrS2s0xY2ZMHaAcovrf5kF3afAQ+BTDwaewdx3CmgzsR2GL+cCIWj29wG/XOkFJPjqCNSTIZSaqw39rEInKHVXr0+CMuEMjfwTdPSoHPaxh8D,iv:nv3yZBGtvCUtsqY73Ddj3a6N6g0Rbt7e95lHcqIYb0Y=,tag:cswmPysh4eCMdnqLv4bAqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM09jdVZhQStmZkdHbWY3
        MVpoTGR6WndNYWw5RzhCN0x5dGxUWUJyYlNBCkEyNVBUVjB6ZXJPNStPMnBrUDZx
        ZEI0MEV3Z3RyR25CbnVYZ2YyMThUU3MKLS0tIHFLOXB4eWk1Y24xVytZTkJwSDlu
        UDRvS0hSL2lzb3I2VThMTWYwRTBmRTgK1q2bxZPqba3GvonYIrqUWWnMNycw/gbd
        yeGjwHg7VUV8zspOrrDPEd0xwRkusJEK3ucHKhC+vgJtI0fVMC5l1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13h4qjyp2axfvzmjzengglzv2h40z3gz88aygdu02y025yg2phqkqjtfp28
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T15:00:03Z"
  mac: ENC[AES256_GCM,data:XXsiG99LDQMm38MQP5RLi/2jvZWKbHPh4By/IH0k3wFQfEcj99thbqHcLAD2G5Ttn/Q6ZIRVkzXoQcGOFnmDvVcQZkauSwyhIc6vJIKHx+rFnl3a4g77kHyhMEvzwhFIp7KY4t6lGVfOSkwtFRG9y8GlDxd6pFJE9CrQNfw152I=,iv:xev2Udwl8H5MDHrsrbDzRgLuJYmvhBLhvAXfZqHOJ4w=,tag:habmMh1MU2KB+5MYMljWhQ==,type:str]
  pgp:
    - created_at: "2026-08-02T15:00:03Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DKaLs6sJalgMSAQdAN23zeA/PWzKQZj4Cv+a9+Fbcoc1UPE4IPxk+i0505gow
        +b8r7ZSCebleOlkarPw67fVZJdaUxykg23OsPEAliKeMHfGmLKM0Wf6E2eyyu4FJ
        0lwBSuD92L0T2t56iKM3rYPQgb8ZxrC5/85mnHqW2vCu69uIl/rNWO6tZIKZBgVT
        jA0Tr82rlfivICuQjKboR8PLPEbIYZ/RS+/j1xjqk9lHpPZwJRfq66jAwKgrFA==
        =n651
        -----END PGP MESSAGE-----
      fp: 82F33E760DDCEB7BB83E2EC3AAC0F2E854677A6F
  version: 3.13.1
