authentik_token: ENC[AES256_GCM,data:ddP5snqaq2AB0IIYXsEGwY8cLgNsZKJoKpsN7CUAnaYhOLCKxvuSMOVAF/qMFfmQi0MNKWIfn3LW+BXL,iv:KwFAVLm9hVphBYuz8TRA5haOcwZhpUy9N01ytIYeZeU=,tag:q8JiXu/LPIfg7sXP5oyJyw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyBHN2x5
            ZitjNGFqenBraWtxdVRFOTR5cTF1QkRNaDZKd1c0d01tMlhLUWdRCml0UzhHYkhj
            dmZqYm4rcllETElNMWgyaUl2eWVUUEZEaW9vZUR5T0F4U00KLS0tIHZLQnRCOENy
            Q0hOK3VDVjAyQVVHeXVNVGNqQVhhN3hWMklRTEczdlNqak0K+H0eZzJU3vuEFaZ+
            tpeZ5tfLlxU9LgVHp3bYnKcvgTbBXK3cnqevHs6/cb2psWMZj2vGb6Qa6My3osKE
            4AAwpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T01:17:33Z"
    mac: ENC[AES256_GCM,data:3bItRM7DnG/qE83aisMbLVRaXyoFN4k466B4QloD2gRZVKJ9UkYCKvwx8JC6YFzRb8bjO3Txx64RmCRygX7ovRUQbujZep3eClAKhoLOTEa1YcCRR2ZPVHKZCrlpqqgv8P+Q0amKsqEvpKNTiJ4QfSJa/+GPZrTSDIbGLtflf2Y=,iv:cbw48XmLJBP3SoW46WKAHs87vYaa1azKw4zftVOcTQs=,tag:Fh+9rhkMjDkZjZGHkvm+9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
