api_token: ENC[AES256_GCM,data:rj9oNdgYueBjBHrosw10gzvmv5uCm1PD7wS+x1m4Fa+ORIyD+jpvyeqlEpfA1ZxT60z28N8=,iv:D4iCCNa1+FNqF987918pJRI1xeksnO+UFdZQua7uOZ8=,tag:o27fUsLQtJa6cgS1Z1GABQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyBGUVQy
        MVpDRC8vTVNMTmNqOS9LWlRNQTBsUmM2ZWFGSXpKUmM1VGlQMkc0CkVNZmFTWmlt
        cys3UzBIbi80aHIxUk5aMGZTa3Y1dUJUNzZBbnhsZ21STUkKLS0tIFhOSkxnK1px
        QXZzWmZva2xrUnFKYmMyZTZNZVNFUkozeVRNUUZFc1R0cVkKdVCwyToZWfVKR2Pw
        eqibs+SYf/9NU1qBlVsDzkASz4M93RlNkPtY5QK5RmZYDhEavICyahvMFaeUEf+Z
        5TgJhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T14:19:32Z"
  mac: ENC[AES256_GCM,data:8mRx+4Fuq4mG1YgrLiTk/p1apjrTxYHRI9ih10tdvEb7bbE2dAj+KCY8yJ5YZF3SrVxDU3RYoZrxzMSSSsjlBwLsI0m+LAWpucx8leAXSsO19ZPsk7IBPFFtiuwUv15MkckWopxsHBT6Z2qbBrJG/RabAIgUItbQUFtIg+Ca4Hg=,iv:I1C+fCtwbwhVvN19FsWnnBOlsUtAqxoPS5RsUHeRzas=,tag:6pXbbI0ANN4zVPB/EDAV2g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
