proxmox:
    endpoint: ENC[AES256_GCM,data:a7hUBKNmTQ==,iv:tfBz9ob0XX9kZTI4fVbBVPOWBGwcCtxRjGbk7pRF+o0=,tag:jb5012ZO2y6e1vNvPtONeQ==,type:str]
    api_token: ENC[AES256_GCM,data:PJ70HzWG7Ebh,iv:AoXIhZRuNTCBkPHcNmWzpfg0cZr5aIOBnFBklzR4HGM=,tag:uILnmcjgHS48wBE9rzTnkg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyA5UGc3
            RjZwMStDQm1EK3FmazZzTGFqaHFnbUJNV3orQ0xTYXREVlN4aEdVCk15UWlmY3J6
            U09EWDV4MzZTR05ORHAyaEZrVjFJaThydnd1bE15UVBQdGsKLS0tIHhIZmNOQ0dN
            TjJyZ2FIVTBoZjkwQm5BdXlrVytPMWdidWRQSCs1a3NoazAKIe9iZX94p6NV/zJ6
            6pQyp63Qy4iZeCGuMakJDyRLXQBLQotrAQ34i2+P2Mljx3UjoO4SUxeMes6wzcwW
            O8NWCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T08:27:32Z"
    mac: ENC[AES256_GCM,data:nhlKxEI1kJ0zxiwUSLQ6bCdiZrlUtaxo5u9Yrv9s4XR/aMFejz3sor+5f8tIP71IwKRo10PlqLOfZC9jAkeQJ7EJbKBGiRb901vHv6rQQhGYzT0+IT5tg4xsTt1VoR1FeF34QnbgenPqaIeTGB5+L9/m4dZWBINC4XJx2RVJ2/c=,iv:MTnHEJK8M7Bu0TFPeg+2YYh0EdYf7qJrh57PitrmXvE=,tag:NvIOdfVA4tFtpMmTP0hpqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
