proxmox:
    endpoint: ENC[AES256_GCM,data:N6jM2BouaXXb9aitUXr5Dt250fkL1vFXbQ==,iv:oUlnAWccqki5EnZEpw2fYL2h23RgrIgLlQosun3c/wA=,tag:R8SaSLuGqx2EYZHxqueXiA==,type:str]
    api_token: ENC[AES256_GCM,data:z2GZVBznmbu+lCuXTqkFP13IQvcQM6TBSBwErvHDglwvd/3hmTUR8qOCs+I7HMKIEiahptzS+Gv3B8Y=,iv:TclAq9Ar9mIqTg/Ox3r5TD9EOCK8cr5AWRbEwlfobwY=,tag:qhv735c6k6Zyzxrt6RAlJw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyA5UGc3
            RjZwMStDQm1EK3FmazZzTGFqaHFnbUJNV3orQ0xTYXREVlN4aEdVCk15UWlmY3J6
            U09EWDV4MzZTR05ORHAyaEZrVjFJaThydnd1bE15UVBQdGsKLS0tIHhIZmNOQ0dN
            TjJyZ2FIVTBoZjkwQm5BdXlrVytPMWdidWRQSCs1a3NoazAKIe9iZX94p6NV/zJ6
            6pQyp63Qy4iZeCGuMakJDyRLXQBLQotrAQ34i2+P2Mljx3UjoO4SUxeMes6wzcwW
            O8NWCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T15:55:06Z"
    mac: ENC[AES256_GCM,data:7wEpPY+QWbfF6dq56laGrfrxRLmtFFC+irC/AT2i/iFDcSdnIn5YF9JE0rfFTt3qD4BLSw1Uob6pgImR3lO6XSq5TMV/oOtED77485gGe1SuMfQ2PKqH2m5LpBmfoDj7rdm/nAfXNKkwqOEQXpoOCQOxUvuPPG1BnsnX9kyMAFk=,iv:MwXwT6QdAgC94nLNQ53rnRlEbUnCeN2MtVnugUCiNgE=,tag:xa5awrKjrKr5oQ6ozCFYiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
