proxmox:
  endpoint: ENC[AES256_GCM,data:MkrN01pN/N8+khWj4lDvgQ+DoDLk9v4=,iv:d3SCdBcorBS66nWLdFYHS58jSc9yWDdd9XFrdq4ESb0=,tag:d5skIHnVysapNbrIiGVbug==,type:str]
  api_token: ENC[AES256_GCM,data:06/BT1GlC7VcmT7Ep/bmGF0IRlQ0qDuwqln3uPF8TKkb/6voPuvYLoOcjEJhOklKJjDIkmoVBw==,iv:jCLGOhJiJcOg7TvrhHVHbCZ9ZxFfdIGm58mx38fD9xs=,tag:smboo81iR+/4hY3r+RWIYQ==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyA5UGc3
        RjZwMStDQm1EK3FmazZzTGFqaHFnbUJNV3orQ0xTYXREVlN4aEdVCk15UWlmY3J6
        U09EWDV4MzZTR05ORHAyaEZrVjFJaThydnd1bE15UVBQdGsKLS0tIHhIZmNOQ0dN
        TjJyZ2FIVTBoZjkwQm5BdXlrVytPMWdidWRQSCs1a3NoazAKIe9iZX94p6NV/zJ6
        6pQyp63Qy4iZeCGuMakJDyRLXQBLQotrAQ34i2+P2Mljx3UjoO4SUxeMes6wzcwW
        O8NWCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T02:42:51Z"
  mac: ENC[AES256_GCM,data:9zsT91/Va3zNhcxSk77EuHl+3xQaqnJZDVtCczrVzpSYEYkuF98TL12O+ytZuLl2B5NzogfUZnQJICk8q1KzGX+y8LPunysX9dTyg0vD4AnfL+VUQau5uxvn1lVSUarNEX33UNMMelZ/hpnCScZjvAwX9hy5E75x42O9haZQZPE=,iv:rGJE9RszVdunYwBNWqXcGz/Z8vi6lMD0EsgkKlMEuF8=,tag:m9mcLuYNgucSrC/ongyrEA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
