proxmox:
    endpoint: ENC[AES256_GCM,data:N6jM2BouaXXb9aitUXr5Dt250fkL1vFXbQ==,iv:oUlnAWccqki5EnZEpw2fYL2h23RgrIgLlQosun3c/wA=,tag:R8SaSLuGqx2EYZHxqueXiA==,type:str]
    api_token: ENC[AES256_GCM,data:06/BT1GlC7VcmT7Ep/bmGF0IRlQ0qDuwqln3uPF8TKkb/6voPuvYLoOcjEJhOklKJjDIkmoVBw==,iv:jCLGOhJiJcOg7TvrhHVHbCZ9ZxFfdIGm58mx38fD9xs=,tag:smboo81iR+/4hY3r+RWIYQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjCf1PpvoMshFkoyjFOYUJ6/pLexwEFqr29COJawkoB
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhvMTdTdyA5UGc3
            RjZwMStDQm1EK3FmazZzTGFqaHFnbUJNV3orQ0xTYXREVlN4aEdVCk15UWlmY3J6
            U09EWDV4MzZTR05ORHAyaEZrVjFJaThydnd1bE15UVBQdGsKLS0tIHhIZmNOQ0dN
            TjJyZ2FIVTBoZjkwQm5BdXlrVytPMWdidWRQSCs1a3NoazAKIe9iZX94p6NV/zJ6
            6pQyp63Qy4iZeCGuMakJDyRLXQBLQotrAQ34i2+P2Mljx3UjoO4SUxeMes6wzcwW
            O8NWCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:52:46Z"
    mac: ENC[AES256_GCM,data:MIGopg6rru2SKXhngY+kPKKvwv1AjeWsJrIqxUXyJoHh61PgG8v+cysDGTSgvwvoSlus0C89kc+RQf9pW3GSLYxVNODRmHYzr0aSfofWsB8+x9MyiPPDqT47wB/jmcdkk6cI2HAWiP5v/vMEjIBCkycMilBTqYCbXObQZ7yFZeM=,iv:RFhSvDCoQYGNV2sLRXHh1TSl1R+HEaFD/OnEgoO/lCo=,tag:+Rh/4IrN3uKzCqx76BNlWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
