name: checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:2.28.5
    env:
      NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run checks
        run: nix develop .#ci --command task check
