services:
  server:
    image: vaultwarden/server:1.37.2@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912

    environment:
      DOMAIN: https://vaultwarden.hovirix.dev
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      SSO_ENABLED: "true"
      SSO_ONLY: "true"
      SSO_AUTH_ONLY_NOT_SESSION: "true"
      SSO_AUTHORITY: https://authentik.hovirix.dev/application/o/vaultwarden/
      SSO_CLIENT_ID_FILE: /run/secrets/vaultwarden_client_id
      SSO_CLIENT_SECRET_FILE: /run/secrets/vaultwarden_client_secret

    secrets:
      - vaultwarden_client_id
      - vaultwarden_client_secret

    networks:
      - traefik-public

    volumes:
      - type: bind
        source: /var/mnt/swarm/vaultwarden
        target: /data

    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS http://localhost/alive >/dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

    deploy:
      replicas: 1

      labels:
        - traefik.enable=true
        - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.hovirix.dev`)
        - traefik.http.routers.vaultwarden.entrypoints=websecure
        - traefik.http.routers.vaultwarden.tls=true
        - traefik.http.routers.vaultwarden.tls.certresolver=cloudflare
        - traefik.http.services.vaultwarden.loadbalancer.server.port=80

      update_config:
        order: start-first
        failure_action: rollback

      rollback_config:
        order: stop-first

      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    name: ingress_traefik-public
    external: true

secrets:
  vaultwarden_client_id:
    external: true

  vaultwarden_client_secret:
    external: true
